package config

import (
	"fmt"
	"regexp"
	"strings"
)

var identifierPattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

type Adapter interface {
	Name() string
	Render(Config) (string, error)
}

func AdapterFor(shell string) (Adapter, error) {
	switch shell {
	case "bash":
		return BashAdapter{}, nil
	case "zsh":
		return ZshAdapter{}, nil
	case "fish":
		return FishAdapter{}, nil
	case "nushell":
		return NushellAdapter{}, nil
	default:
		return nil, fmt.Errorf("unsupported shell: %q", shell)
	}
}

func renderHeader(shell string) string {
	return fmt.Sprintf(
		"# Generated by uniShell for %s. Do not edit.\n\n",
		shell,
	)
}

func renderPOSIXValue(value string) string {
	return "'" + strings.ReplaceAll(
		value,
		"'",
		"'\"'\"'",
	) + "'"
}

func renderFishValue(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, `'`, `\'`)

	return "'" + value + "'"
}

func validIdentifier(value string) bool {
	return identifierPattern.MatchString(value)
}
