package config

import (
	"strings"
	"testing"
)

func TestFishRender(t *testing.T) {
	cfg := Config{
		Environment: map[string]string{
			"EDITOR": "vim",
		},
		Path: PathConfig{
			Add: []string{
				"$HOME/.local/bin",
			},
		},
		Aliases: map[string]string{
			"gs": "git status",
		},
	}

	got, err := (FishAdapter{}).Render(cfg)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := []string{
		`set -gx EDITOR 'vim'`,
		`set -gx PATH '$HOME/.local/bin' $PATH`,
		`alias gs 'git status'`,
	}

	for _, line := range want {
		if !strings.Contains(got, line) {
			t.Fatalf("Render() missing %q:\n%s", line, got)
		}
	}
}

func TestFishRenderPreservesPathOrderAndEscapesValues(
	t *testing.T,
) {
	cfg := Config{
		Environment: map[string]string{
			"EDITOR": `it's "vim"`,
		},
		Path: PathConfig{
			Add: []string{
				`$HOME/first`,
				`$HOME/second`,
			},
		},
		Aliases: map[string]string{
			"say": `echo "it's ready"`,
		},
	}

	got, err := (FishAdapter{}).Render(cfg)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := []string{
		`set -gx EDITOR 'it\'s "vim"'`,
		`set -gx PATH '$HOME/first' '$HOME/second' $PATH`,
		`alias say 'echo "it\'s ready"'`,
	}

	for _, line := range want {
		if !strings.Contains(got, line) {
			t.Fatalf("Render() missing %q:\n%s", line, got)
		}
	}
}

func TestFishRenderExactOutput(t *testing.T) {
	cfg := Config{
		Environment: map[string]string{
			"EDITOR": "vim",
			"VISUAL": "$EDITOR",
		},
		Path: PathConfig{
			Add: []string{
				"$HOME/.local/bin",
				"$HOME/bin",
			},
		},
		Aliases: map[string]string{
			"gs": "git status",
			"ll": "ls -lah",
		},
	}

	got, err := (FishAdapter{}).Render(cfg)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := `# Generated by uniShell for fish. Do not edit.

set -gx EDITOR 'vim'
set -gx VISUAL '$EDITOR'
set -gx PATH '$HOME/.local/bin' '$HOME/bin' $PATH
alias gs 'git status'
alias ll 'ls -lah'
`

	if got != want {
		t.Fatalf("Render() = %q, want %q", got, want)
	}
}
