package config

import (
	"strings"
	"testing"
)

func TestNushellRender(t *testing.T) {
	cfg := Config{
		Environment: map[string]string{
			"EDITOR": "vim",
		},
		Path: PathConfig{
			Add: []string{
				"$HOME/.local/bin",
			},
		},
		Aliases: map[string]string{
			"gs": "git status",
		},
	}

	got, err := (NushellAdapter{}).Render(cfg)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := []string{
		`$env.EDITOR = "vim"`,
		`$env.PATH = ("$HOME/.local/bin" | append $env.PATH)`,
		`alias gs = git status`,
	}

	for _, line := range want {
		if !strings.Contains(got, line) {
			t.Fatalf("Render() missing %q:\n%s", line, got)
		}
	}
}

func TestNushellRenderPreservesPathOrderAndEscapesValues(
	t *testing.T,
) {
	cfg := Config{
		Environment: map[string]string{
			"EDITOR": `it's "vim"\editor`,
		},
		Path: PathConfig{
			Add: []string{
				`$HOME/first`,
				`$HOME/second`,
			},
		},
		Aliases: map[string]string{
			"say": `echo "it's ready"`,
		},
	}

	got, err := (NushellAdapter{}).Render(cfg)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := []string{
		`$env.EDITOR = "it's \"vim\"\\editor"`,
		`$env.PATH = ("$HOME/first" | append "$HOME/second" | append $env.PATH)`,
		`alias say = echo "it's ready"`,
	}

	for _, line := range want {
		if !strings.Contains(got, line) {
			t.Fatalf("Render() missing %q:\n%s", line, got)
		}
	}
}

func TestNushellRenderExactOutput(t *testing.T) {
	cfg := Config{
		Environment: map[string]string{
			"EDITOR": "vim",
			"VISUAL": "$EDITOR",
		},
		Path: PathConfig{
			Add: []string{
				"$HOME/.local/bin",
				"$HOME/bin",
			},
		},
		Aliases: map[string]string{
			"gs": "git status",
			"ll": "ls -lah",
		},
	}

	got, err := (NushellAdapter{}).Render(cfg)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := `# Generated by uniShell for nushell. Do not edit.

$env.EDITOR = "vim"
$env.VISUAL = "$EDITOR"
$env.PATH = ("$HOME/.local/bin" | append "$HOME/bin" | append $env.PATH)
alias gs = git status
alias ll = ls -lah
`

	if got != want {
		t.Fatalf("Render() = %q, want %q", got, want)
	}
}
