package config

import (
	"strings"
	"testing"
)

func TestZshRender(t *testing.T) {
	cfg := Config{
		Environment: map[string]string{
			"EDITOR": "vim",
		},
		Path: PathConfig{
			Add: []string{
				"$HOME/.local/bin",
			},
		},
		Aliases: map[string]string{
			"gs": "git status",
		},
	}

	got, err := (ZshAdapter{}).Render(cfg)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := []string{
		`export EDITOR='vim'`,
		`export PATH='$HOME/.local/bin':"$PATH"`,
		`alias gs='git status'`,
	}

	for _, line := range want {
		if !strings.Contains(got, line) {
			t.Fatalf("Render() missing %q:\n%s", line, got)
		}
	}
}

func TestZshRenderPreservesPathOrderAndEscapesValues(
	t *testing.T,
) {
	cfg := Config{
		Environment: map[string]string{
			"EDITOR": `it's "vim"`,
		},
		Path: PathConfig{
			Add: []string{
				`$HOME/first`,
				`$HOME/second`,
			},
		},
		Aliases: map[string]string{
			"say": `echo "it's ready"`,
		},
	}

	got, err := (ZshAdapter{}).Render(cfg)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := []string{
		`export EDITOR='it'"'"'s "vim"'`,
		`export PATH='$HOME/first':'$HOME/second':"$PATH"`,
		`alias say='echo "it'"'"'s ready"'`,
	}

	for _, line := range want {
		if !strings.Contains(got, line) {
			t.Fatalf("Render() missing %q:\n%s", line, got)
		}
	}
}

func TestZshRenderExactOutput(t *testing.T) {
	cfg := Config{
		Environment: map[string]string{
			"EDITOR": "vim",
			"VISUAL": "$EDITOR",
		},
		Path: PathConfig{
			Add: []string{
				"$HOME/.local/bin",
				"$HOME/bin",
			},
		},
		Aliases: map[string]string{
			"gs": "git status",
			"ll": "ls -lah",
		},
	}

	got, err := (ZshAdapter{}).Render(cfg)
	if err != nil {
		t.Fatalf("Render() returned error: %v", err)
	}

	want := `# Generated by uniShell for zsh. Do not edit.

export EDITOR='vim'
export VISUAL='$EDITOR'
export PATH='$HOME/.local/bin':'$HOME/bin':"$PATH"
alias gs='git status'
alias ll='ls -lah'
`

	if got != want {
		t.Fatalf("Render() = %q, want %q", got, want)
	}
}
