[[tools]]
name = "bat"

[[tools.artifacts]]
version = "0.26.1"
platform = "linux"
architecture = "amd64"
archive_type = "tar.gz"
binary_path = "bat-v0.26.1-x86_64-unknown-linux-musl/bat"
binary_name = "bat"
checksum = ""

[tools.artifacts.validation]
static_elf = true
musl = true
executable = true

[tools.artifacts.source]
kind = "github-release"

[tools.artifacts.source.github_release]
owner = "sharkdp"
repository = "bat"
release = "v0.26.1"
asset = "bat-v0.26.1-x86_64-unknown-linux-musl.tar.gz"
