[[tools]]
name = "gdu"

[[tools.artifacts]]
version = "5.37.0"
platform = "linux"
architecture = "amd64"
archive_type = "tgz"
binary_path = "gdu_linux_amd64_static"
binary_name = "gdu"
checksum = ""

[tools.artifacts.validation]
static_elf = true
musl = true
executable = true

[tools.artifacts.source]
kind = "github-release"

[tools.artifacts.source.github_release]
owner = "dundee"
repository = "gdu"
release = "v5.37.0"
asset = "gdu_linux_amd64_static.tgz"
