[[tools]]
name = "k9s"

[[tools.artifacts]]
version = "0.51.0"
platform = "linux"
architecture = "amd64"
archive_type = "tar.gz"
binary_path = "k9s"
binary_name = "ks"
checksum = ""

[tools.artifacts.validation]
static_elf = true
musl = true
executable = true

[tools.artifacts.source]
kind = "github-release"

[tools.artifacts.source.github_release]
owner = "derailed"
repository = "k9s"
release = "v0.51.0"
asset = "k9s_Linux_amd64.tar.gz"
