##### General Settings #####
# SPECIFY THE SHELL TO USE
set-option -g default-command "exec env AUTH=$AUTH bash --rcfile $usHOME/.lesscache"

# Enable tmux status bar
set -g status on

# Enable TMUX Clipboard
set -g set-clipboard on

# Allow passthrough for terminal features (useful for nested tmux or advanced terminal support)
set -gq allow-passthrough on

# Set default terminal to support 256 colors
set -g default-terminal "xterm-256color"

# Improve color support for true-color terminals
set-option -ga terminal-overrides ",*:Tc"
set -ga terminal-features ",xterm-256color:RGB"

# Increase scrollback history limit (default is 2000)
set-option -g history-limit 1000000

##### Status Bar Configuration #####
# Set status bar update interval (in seconds)
set -g status-interval 2

# Status bar styling: white bold text on a dark gray background
set -g status-style fg=white,bold,bg=colour8

# Center window list (uncomment if desired)
# set-option -g status-justify centre

# Left side of status bar: show session name, window index, and pane index
set -g status-left-length 15
set -g status-left ' #[fg=colour118]#S.#I.#P #[fg=white]| '

# Right side of status bar: dynamic system info + time and date
set -g status-right-length 200
set -g status-right '#[fg=colour118,bold,bg=color0] #(if command -v sysmon > /dev/null 2>&1; then sysmon; else uptime -p; fi) #[fg=colour15,bg=color8] @ %R - %d %b '

##### Window and Pane Styling #####
# Style for inactive windows in window list: yellow text on gray background
setw -g window-status-style fg=color11,bg=colour8

# Style for active window in window list: bright blue bold text on dark background
setw -g window-status-current-style fg=colour117,bold,bg=colour235

# Pane border colors: green for inactive, white on yellow for active
setw -g pane-border-style fg=green,bg=black
setw -g pane-active-border-style fg=white,bg=yellow

# Pane content styling:
#   - Active pane: white text on black
#   - Inactive pane: blue text on gray
setw -g window-active-style fg=white,bg=black
setw -g window-style fg=colour12,bg=colour237

# Message/command prompt styling
set -g message-style fg=white,bold,bg=colour8

##### Key Bindings and Modes #####
# Use Vi-style key bindings in copy mode
setw -g mode-keys vi

# Split panes vertically (using ")
bind '"' split-window -v -c "#{pane_current_path}"

# Split panes horizontally (using %)
bind % split-window -h -c "#{pane_current_path}"

# Create new windows in the same directory (using c) | Commented so that it Always start new windows at '$HOME'
# bind c new-window -c "#{pane_current_path}"


# vim: set ft=tmux:
