package shell

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"gitlab.com/mainops/uniShell/internal/shell/config"
	"gitlab.com/mainops/uniShell/internal/shell/profile"
)

func TestPrepareProfileStartupRendersSharedAndProfile(
	t *testing.T,
) {
	runtimeDir := t.TempDir()

	loaded := profile.Loaded{
		Shared: config.Config{
			Environment: map[string]string{
				"EDITOR": "vim",
			},
			Path: config.PathConfig{
				Add: []string{
					"$HOME/.local/bin",
				},
			},
			Aliases: map[string]string{
				"ll": "ls -lah",
			},
		},
		Profile: []byte(
			"echo profile\n",
		),
	}

	startup, err := PrepareProfileStartup(
		runtimeDir,
		"bash",
		"server",
		loaded,
		true,
	)
	if err != nil {
		t.Fatalf(
			"PrepareProfileStartup() returned error: %v",
			err,
		)
	}

	wantPath := filepath.Join(
		runtimeDir,
		"config",
		"shell-generated",
		"server.bash",
	)

	wantStartup := Startup{
		Args: []string{
			"--noprofile",
			"--rcfile",
			wantPath,
		},
	}

	if !reflect.DeepEqual(startup, wantStartup) {
		t.Fatalf(
			"startup = %#v, want %#v",
			startup,
			wantStartup,
		)
	}

	data, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf(
			"ReadFile(%q) returned error: %v",
			wantPath,
			err,
		)
	}

	want := `# Generated by uniShell for bash. Do not edit.

export EDITOR='vim'
export PATH='$HOME/.local/bin':"$PATH"
alias ll='ls -lah'
echo profile
`

	if string(data) != want {
		t.Fatalf(
			"startup file = %q, want %q",
			string(data),
			want,
		)
	}
}

func TestPrepareProfileStartupExcludesSharedConfiguration(
	t *testing.T,
) {
	runtimeDir := t.TempDir()

	loaded := profile.Loaded{
		Shared: config.Config{
			Environment: map[string]string{
				"EDITOR": "vim",
			},
		},
		Profile: []byte(
			"echo profile\n",
		),
	}

	_, err := PrepareProfileStartup(
		runtimeDir,
		"bash",
		"home",
		loaded,
		false,
	)
	if err != nil {
		t.Fatalf(
			"PrepareProfileStartup() returned error: %v",
			err,
		)
	}

	path := filepath.Join(
		runtimeDir,
		"config",
		"shell-generated",
		"home.bash",
	)

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf(
			"ReadFile(%q) returned error: %v",
			path,
			err,
		)
	}

	want := "echo profile\n"

	if string(data) != want {
		t.Fatalf(
			"startup file = %q, want %q",
			string(data),
			want,
		)
	}
}

func TestPrepareProfileStartupSupportsNushell(
	t *testing.T,
) {
	runtimeDir := t.TempDir()

	loaded := profile.Loaded{
		Shared: config.Config{
			Environment: map[string]string{
				"EDITOR": "nvim",
			},
		},
		Profile: []byte(
			"print 'profile'\n",
		),
	}

	startup, err := PrepareProfileStartup(
		runtimeDir,
		"nushell",
		"server",
		loaded,
		true,
	)
	if err != nil {
		t.Fatalf(
			"PrepareProfileStartup() returned error: %v",
			err,
		)
	}

	wantPath := filepath.Join(
		runtimeDir,
		"config",
		"shell-generated",
		"server.nushell",
	)

	wantStartup := Startup{
		Args: []string{
			"--config",
			wantPath,
		},
	}

	if !reflect.DeepEqual(startup, wantStartup) {
		t.Fatalf(
			"startup = %#v, want %#v",
			startup,
			wantStartup,
		)
	}

	data, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf(
			"ReadFile(%q) returned error: %v",
			wantPath,
			err,
		)
	}

	want := `# Generated by uniShell for nushell. Do not edit.

$env.EDITOR = "nvim"
print 'profile'
`

	if string(data) != want {
		t.Fatalf(
			"startup file = %q, want %q",
			string(data),
			want,
		)
	}
}

func TestPrepareProfileStartupRejectsEmptyRuntimeDirectory(
	t *testing.T,
) {
	_, err := PrepareProfileStartup(
		"",
		"bash",
		"server",
		profile.Loaded{},
		true,
	)

	if err == nil {
		t.Fatal("PrepareProfileStartup() returned nil error")
	}

	want := "shell startup runtime directory cannot be empty"

	if err.Error() != want {
		t.Fatalf("error = %q, want %q", err.Error(), want)
	}
}

func TestPrepareProfileStartupRejectsEmptyShell(
	t *testing.T,
) {
	_, err := PrepareProfileStartup(
		t.TempDir(),
		"",
		"server",
		profile.Loaded{},
		true,
	)

	if err == nil {
		t.Fatal("PrepareProfileStartup() returned nil error")
	}

	want := "shell name cannot be empty"

	if err.Error() != want {
		t.Fatalf("error = %q, want %q", err.Error(), want)
	}
}

func TestPrepareProfileStartupRejectsEmptyProfile(
	t *testing.T,
) {
	_, err := PrepareProfileStartup(
		t.TempDir(),
		"bash",
		"",
		profile.Loaded{},
		true,
	)

	if err == nil {
		t.Fatal("PrepareProfileStartup() returned nil error")
	}

	want := "shell profile name cannot be empty"

	if err.Error() != want {
		t.Fatalf("error = %q, want %q", err.Error(), want)
	}
}
