package shell

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"gitlab.com/mainops/uniShell/internal/shell/config"
	"gitlab.com/mainops/uniShell/internal/shell/profile"
)

func TestPrepareProfileStartupRendersSharedAndProfile(
	t *testing.T,
) {
	runtimeDir := t.TempDir()

	loaded := profile.Loaded{
		Shared: config.Config{
			Environment: map[string]string{
				"EDITOR": "vim",
			},
			Path: config.PathConfig{
				Add: []string{
					"$HOME/.local/bin",
				},
			},
			Aliases: map[string]string{
				"ll": "ls -lah",
			},
		},
		Profile: []byte(
			"echo profile\n",
		),
	}

	startup, err := PrepareProfileStartup(
		runtimeDir,
		"bash",
		"server",
		loaded,
		true,
		nil,
		nil,
	)
	if err != nil {
		t.Fatalf(
			"PrepareProfileStartup() returned error: %v",
			err,
		)
	}

	wantPath := filepath.Join(
		runtimeDir,
		"config",
		"shell-generated",
		"server.bash",
	)

	wantStartup := Startup{
		Args: []string{
			"--noprofile",
			"--rcfile",
			wantPath,
		},
	}

	if !reflect.DeepEqual(startup, wantStartup) {
		t.Fatalf(
			"startup = %#v, want %#v",
			startup,
			wantStartup,
		)
	}

	data, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf(
			"ReadFile(%q) returned error: %v",
			wantPath,
			err,
		)
	}

	want := `# Generated by uniShell for bash. Do not edit.

export EDITOR='vim'
export PATH='$HOME/.local/bin':"$PATH"
alias ll='ls -lah'
echo profile
`

	if string(data) != want {
		t.Fatalf(
			"startup file = %q, want %q",
			string(data),
			want,
		)
	}
}

func TestPrepareProfileStartupResolvesSharedConfiguration(
	t *testing.T,
) {
	runtimeDir := t.TempDir()

	loaded := profile.Loaded{
		Shared: config.Config{
			Environment: map[string]string{
				"BASE_DIR": "${HOME}/.local",
				"BIN_DIR":  "${BASE_DIR}/bin",
			},
			Path: config.PathConfig{
				Add: []string{
					"${BIN_DIR}",
				},
			},
			Aliases: map[string]string{
				"work": "cd ${BASE_DIR}",
			},
		},
	}

	startup, err := PrepareProfileStartup(
		runtimeDir,
		"bash",
		"server",
		loaded,
		true,
		map[string]string{},
		map[string]string{
			"HOME": "/home/test",
		},
	)
	if err != nil {
		t.Fatalf(
			"PrepareProfileStartup() returned error: %v",
			err,
		)
	}

	wantPath := filepath.Join(
		runtimeDir,
		"config",
		"shell-generated",
		"server.bash",
	)

	data, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf(
			"ReadFile(%q) returned error: %v",
			wantPath,
			err,
		)
	}

	want := `# Generated by uniShell for bash. Do not edit.

export BASE_DIR='/home/test/.local'
export BIN_DIR='/home/test/.local/bin'
export PATH='/home/test/.local/bin':"$PATH"
alias work='cd /home/test/.local'
`

	if string(data) != want {
		t.Fatalf(
			"startup file = %q, want %q",
			string(data),
			want,
		)
	}

	wantStartup := Startup{
		Args: []string{
			"--noprofile",
			"--rcfile",
			wantPath,
		},
	}

	if !reflect.DeepEqual(startup, wantStartup) {
		t.Fatalf(
			"startup = %#v, want %#v",
			startup,
			wantStartup,
		)
	}
}

func TestPrepareProfileStartupResolvesSharedConfigurationAcrossAdapters(t *testing.T) {
	tests := []struct {
		name      string
		shellName string
		expected  string
	}{
		{
			name:      "zsh",
			shellName: "zsh",
			expected: `# Generated by uniShell for zsh. Do not edit.

export BASE_DIR='/home/test/.local'
export BIN_DIR='/home/test/.local/bin'
export PATH='/home/test/.local/bin':"$PATH"
alias work='cd /home/test/.local'
`,
		},
		{
			name:      "fish",
			shellName: "fish",
			expected: `# Generated by uniShell for fish. Do not edit.

set -gx BASE_DIR '/home/test/.local'
set -gx BIN_DIR '/home/test/.local/bin'
set -gx PATH '/home/test/.local/bin' $PATH
alias work 'cd /home/test/.local'
`,
		},
		{
			name:      "nushell",
			shellName: "nushell",
			expected: `# Generated by uniShell for nushell. Do not edit.

$env.BASE_DIR = "/home/test/.local"
$env.BIN_DIR = "/home/test/.local/bin"
$env.PATH = ("/home/test/.local/bin" | append $env.PATH)
alias work = cd /home/test/.local
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			runtimeDir := t.TempDir()

			loaded := profile.Loaded{
				Shared: config.Config{
					Environment: map[string]string{
						"BASE_DIR": "${HOME}/.local",
						"BIN_DIR":  "${BASE_DIR}/bin",
					},
					Path: config.PathConfig{
						Add: []string{"${BIN_DIR}"},
					},
					Aliases: map[string]string{
						"work": "cd ${BASE_DIR}",
					},
				},
			}

			_, err := PrepareProfileStartup(
				runtimeDir,
				tt.shellName,
				"default",
				loaded,
				true,
				nil,
				map[string]string{
					"HOME": "/home/test",
				},
			)
			if err != nil {
				t.Fatalf("PrepareProfileStartup() returned error: %v", err)
			}

			data, err := os.ReadFile(
				filepath.Join(
					runtimeDir,
					"config",
					"shell-generated",
					"default."+tt.shellName,
				),
			)
			if err != nil {
				t.Fatalf("ReadFile() returned error: %v", err)
			}

			if got := string(data); got != tt.expected {
				t.Fatalf(
					"startup file = %q, want %q",
					got,
					tt.expected,
				)
			}
		})
	}
}

func TestPrepareProfileStartupRejectsUnresolvedConfigurationVariable(
	t *testing.T,
) {
	runtimeDir := t.TempDir()

	loaded := profile.Loaded{
		Shared: config.Config{
			Environment: map[string]string{
				"EDITOR": "${MISSING_EDITOR}",
			},
		},
	}

	_, err := PrepareProfileStartup(
		runtimeDir,
		"bash",
		"server",
		loaded,
		true,
		nil,
		nil,
	)
	if err == nil {
		t.Fatal("PrepareProfileStartup() returned nil error")
	}

	want := `resolve shared shell configuration: resolve environment variable "EDITOR": variable "MISSING_EDITOR" not found in configuration, session environment, or system environment`

	if err.Error() != want {
		t.Fatalf(
			"error = %q, want %q",
			err.Error(),
			want,
		)
	}
}

func TestPrepareProfileStartupExcludesSharedConfiguration(
	t *testing.T,
) {
	runtimeDir := t.TempDir()

	loaded := profile.Loaded{
		Shared: config.Config{
			Environment: map[string]string{
				"EDITOR": "vim",
			},
		},
		Profile: []byte(
			"echo profile\n",
		),
	}

	_, err := PrepareProfileStartup(
		runtimeDir,
		"bash",
		"home",
		loaded,
		false,
		nil,
		nil,
	)
	if err != nil {
		t.Fatalf(
			"PrepareProfileStartup() returned error: %v",
			err,
		)
	}

	path := filepath.Join(
		runtimeDir,
		"config",
		"shell-generated",
		"home.bash",
	)

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf(
			"ReadFile(%q) returned error: %v",
			path,
			err,
		)
	}

	want := "echo profile\n"

	if string(data) != want {
		t.Fatalf(
			"startup file = %q, want %q",
			string(data),
			want,
		)
	}
}

func TestPrepareProfileStartupSupportsNushell(
	t *testing.T,
) {
	runtimeDir := t.TempDir()

	loaded := profile.Loaded{
		Shared: config.Config{
			Environment: map[string]string{
				"EDITOR": "nvim",
			},
		},
		Profile: []byte(
			"print 'profile'\n",
		),
	}

	startup, err := PrepareProfileStartup(
		runtimeDir,
		"nushell",
		"server",
		loaded,
		true,
		nil,
		nil,
	)
	if err != nil {
		t.Fatalf(
			"PrepareProfileStartup() returned error: %v",
			err,
		)
	}

	wantPath := filepath.Join(
		runtimeDir,
		"config",
		"shell-generated",
		"server.nushell",
	)

	wantStartup := Startup{
		Args: []string{
			"--config",
			wantPath,
		},
	}

	if !reflect.DeepEqual(startup, wantStartup) {
		t.Fatalf(
			"startup = %#v, want %#v",
			startup,
			wantStartup,
		)
	}

	data, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf(
			"ReadFile(%q) returned error: %v",
			wantPath,
			err,
		)
	}

	want := `# Generated by uniShell for nushell. Do not edit.

$env.EDITOR = "nvim"
print 'profile'
`

	if string(data) != want {
		t.Fatalf(
			"startup file = %q, want %q",
			string(data),
			want,
		)
	}
}

func TestPrepareProfileStartupRejectsEmptyRuntimeDirectory(
	t *testing.T,
) {
	_, err := PrepareProfileStartup(
		"",
		"bash",
		"server",
		profile.Loaded{},
		true,
		nil,
		nil,
	)

	if err == nil {
		t.Fatal("PrepareProfileStartup() returned nil error")
	}

	want := "shell startup runtime directory cannot be empty"

	if err.Error() != want {
		t.Fatalf("error = %q, want %q", err.Error(), want)
	}
}

func TestPrepareProfileStartupRejectsEmptyShell(
	t *testing.T,
) {
	_, err := PrepareProfileStartup(
		t.TempDir(),
		"",
		"server",
		profile.Loaded{},
		true,
		nil,
		nil,
	)

	if err == nil {
		t.Fatal("PrepareProfileStartup() returned nil error")
	}

	want := "shell name cannot be empty"

	if err.Error() != want {
		t.Fatalf("error = %q, want %q", err.Error(), want)
	}
}

func TestPrepareProfileStartupSupportsSharedConfigurationWithoutProfile(
	t *testing.T,
) {
	runtimeDir := t.TempDir()

	loaded := profile.Loaded{
		Shared: config.Config{
			Environment: map[string]string{
				"EDITOR": "vim",
			},
		},
	}

	startup, err := PrepareProfileStartup(
		runtimeDir,
		"bash",
		"",
		loaded,
		true,
		nil,
		nil,
	)
	if err != nil {
		t.Fatalf(
			"PrepareProfileStartup() returned error: %v",
			err,
		)
	}

	wantPath := filepath.Join(
		runtimeDir,
		"config",
		"shell-generated",
		".bash",
	)

	wantStartup := Startup{
		Args: []string{
			"--noprofile",
			"--rcfile",
			wantPath,
		},
	}

	if !reflect.DeepEqual(startup, wantStartup) {
		t.Fatalf(
			"startup = %#v, want %#v",
			startup,
			wantStartup,
		)
	}

	data, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf(
			"ReadFile(%q) returned error: %v",
			wantPath,
			err,
		)
	}

	want := `# Generated by uniShell for bash. Do not edit.

export EDITOR='vim'
`

	if string(data) != want {
		t.Fatalf(
			"startup file = %q, want %q",
			string(data),
			want,
		)
	}
}
