package main

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
)

func generateBundleSource(output string, bundleData []byte) error {
	var source bytes.Buffer

	source.WriteString("//go:build unishell_bundle\n\n")
	source.WriteString("package bundle\n\n")
	source.WriteString("// Code generated by bundle-builder. DO NOT EDIT.\n")
	source.WriteString("func generatedBundle() []byte {\n")
	source.WriteString("\treturn []byte{\n")

	for offset := 0; offset < len(bundleData); offset += 16 {
		end := offset + 16
		if end > len(bundleData) {
			end = len(bundleData)
		}

		source.WriteString("\t\t")

		for index, b := range bundleData[offset:end] {
			if index > 0 {
				source.WriteString(" ")
			}

			fmt.Fprintf(
				&source,
				"0x%s,",
				hex.EncodeToString([]byte{b}),
			)
		}

		source.WriteString("\n")
	}

	source.WriteString("\t}\n")
	source.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(output), 0700); err != nil {
		return fmt.Errorf("create generated bundle directory: %w", err)
	}

	file, err := os.OpenFile(
		output,
		os.O_WRONLY|os.O_CREATE|os.O_TRUNC,
		0600,
	)
	if err != nil {
		return fmt.Errorf("create generated bundle source: %w", err)
	}

	if _, err := file.Write(source.Bytes()); err != nil {
		_ = file.Close()
		return fmt.Errorf("write generated bundle source: %w", err)
	}

	if err := file.Close(); err != nil {
		return fmt.Errorf("close generated bundle source: %w", err)
	}

	return nil
}
